import { LayoutPersonality } from './types';

export const LAYOUT_PERSONALITIES: LayoutPersonality[] = [
  {
    name: 'Dark Cinematic',
    heroVariant: 'dark',
    testimonialVariant: 'dark',
    featuresVariant: 'dark',
    statsVariant: 'dark',
    buttonVariant: 'primary',
    optinVariant: 'dark',
    structureBias: 'Open with drama. Dark hero or hero-dark block, cinematic image, stats early. Proof near top. Build urgency steadily.',
    visualMood: 'Premium, mysterious, high-stakes. Like a luxury product launch. Dark sections alternate with light.',
    blockOrderBias: 'hero-dark → image → stats → paragraph → testimonial → features → testimonial-grid → countdown → guarantee → button',
    articleVariant: 'dark',
    pullQuoteVariant: 'dark',
  },
  {
    name: 'Clean Editorial',
    heroVariant: 'minimal',
    testimonialVariant: 'quotes',
    featuresVariant: 'list',
    statsVariant: 'light',
    buttonVariant: 'ghost',
    optinVariant: 'centered',
    structureBias: 'Lead with typography and content authority. Editorial article header, long-form paragraphs, proof woven in. Single strong CTA near end.',
    visualMood: 'Refined, journalistic, trustworthy. Like the New York Times meets Wirecutter. White space is your friend.',
    blockOrderBias: 'article → table-of-contents → image → paragraph → pull-quote → stats → testimonial → features → paragraph → testimonial-grid → article-verdict → guarantee → button → author-bio → article-end',
    articleVariant: 'nyt',
    pullQuoteVariant: 'minimal',
  },
  {
    name: 'Bold Sales Machine',
    heroVariant: 'centered',
    testimonialVariant: 'featured',
    featuresVariant: 'numbered',
    statsVariant: 'inline',
    buttonVariant: 'wide',
    optinVariant: 'split',
    structureBias: 'Maximum urgency and persuasion. Strong hero, stats immediately after, bold feature benefits, multiple CTAs, countdown high on page.',
    visualMood: 'Energetic, urgent, results-driven. Like a ClickFunnels high-ticket offer. Every section sells.',
    blockOrderBias: 'attention-bar → article → stats → button → features → bullets → testimonial-grid → countdown → comparison → guarantee → faq → button',
    articleVariant: 'classic',
    pullQuoteVariant: 'accent',
  },
  {
    name: 'Magazine Feature',
    heroVariant: 'magazine',
    testimonialVariant: 'cards',
    featuresVariant: 'list',
    statsVariant: 'light',
    buttonVariant: 'ghost',
    optinVariant: 'centered',
    structureBias: 'Editorial feel throughout. Article intro with TOC, callouts like magazine sidebars, testimonials woven into narrative, verdict block near end.',
    visualMood: 'Editorial, credible, authoritative. Like a Forbes or Wired feature article that naturally recommends a product.',
    blockOrderBias: 'attention-bar → article (magazine variant) → table-of-contents → image → paragraph → callout → pull-quote → testimonial → paragraph → stats → features → callout → testimonial-grid → article-verdict → faq → guarantee → button → author-bio → article-end',
    articleVariant: 'magazine',
    pullQuoteVariant: 'accent',
  },
  {
    name: 'Split Authority',
    heroVariant: 'split',
    testimonialVariant: 'quotes',
    featuresVariant: 'cards',
    statsVariant: 'dark',
    buttonVariant: 'primary',
    optinVariant: 'dark',
    structureBias: 'Data and proof drive the page. Split-screen opener for contrast. Stats immediately. Comparison block as centrepiece. Guarantee prominent.',
    visualMood: 'Professional, analytical, data-first. Like a SaaS landing page meets affiliate review. Clean grids, strong numbers.',
    blockOrderBias: 'article → stats → paragraph → comparison → bullets → testimonial-grid → callout → features → article-verdict → guarantee → countdown → badge → button',
    articleVariant: 'classic',
    pullQuoteVariant: 'minimal',
  },
  {
    name: 'Story-Driven',
    heroVariant: 'minimal',
    testimonialVariant: 'featured',
    featuresVariant: 'numbered',
    statsVariant: 'inline',
    buttonVariant: 'wide',
    optinVariant: 'split',
    structureBias: 'Narrative-first. Open with a story (dropcap opening paragraph), build through long paragraphs, reveal the solution through numbered steps, close with social proof wall.',
    visualMood: 'Warm, relatable, personal. Like Russell Brunson bridge page meets long-form storytelling. The reader feels understood.',
    blockOrderBias: 'article → dropcap-paragraph (story hook) → paragraph → pull-quote → image → paragraph → features (numbered steps) → testimonial → stats → testimonial-grid → article-verdict → countdown → guarantee → button → author-bio',
    articleVariant: 'minimal',
    pullQuoteVariant: 'accent',
  },
];